syntax = "proto3";

option csharp_namespace = "SomeShop.Catalog.V1";

import "SomeShop.Common.Proto/Protos/money.proto";

package catalog;

service Service {
  rpc GetProducts (GetProductsRequest) returns (GetProductsResponse);
  rpc GetProductPrice (GetProductPriceRequest) returns (GetProductPriceResponse);
}

message GetProductsRequest {
}

message GetProductsResponse {
  repeated Product products = 1;
  
  message Product {
    string id = 1;
    string name = 2;
    common.Money price = 3;
  }
}

message GetProductPriceRequest {
  string product_id = 1;
}

message GetProductPriceResponse {
  string product_id = 1;
  common.Money price = 2;
}
