// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SomeShop.StockManagement.EF;

#nullable disable

namespace SomeShop.StockManagement.EF.Migrations
{
    [DbContext(typeof(StockManagementDbContext))]
    partial class StockManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stock_management")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SomeShop.StockManagement.Domain.Reservation", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FailReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fail_reason");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("OrderId")
                        .HasName("pk_reservations");

                    b.ToTable("reservations", "stock_management");
                });

            modelBuilder.Entity("SomeShop.StockManagement.Domain.ReservationItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("pk_reservation_items");

                    b.ToTable("reservation_items", "stock_management");
                });

            modelBuilder.Entity("SomeShop.StockManagement.Domain.StockItem", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("Available")
                        .HasColumnType("bigint")
                        .HasColumnName("available");

                    b.Property<long>("Reserved")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProductId")
                        .HasName("pk_stock_items");

                    b.ToTable("stock_items", "stock_management");
                });

            modelBuilder.Entity("SomeShop.StockManagement.Domain.ReservationItem", b =>
                {
                    b.HasOne("SomeShop.StockManagement.Domain.Reservation", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_items_reservations_order_id");
                });

            modelBuilder.Entity("SomeShop.StockManagement.Domain.Reservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
